# GitLab CI/CD configuration
# P13@3DS.com
# please read Gitlab-CI-Setup.md to enable CI/CD on the repository

stages:
    - deploy

##########################
# zip_to_s3 (master only)
# stage: deploy
# Push widget to AWS S3

zip_to_s3:
    stage: deploy
    image: dswidgetlab/awscli
    tags:
        - widgetlab
    only:
        - master
    script:
        - zip -r /home/s3/$CI_PROJECT_NAME.zip . -x@.zipignore
        - export S3_DST=s3://btcc/widget-lab/templates/
        - aws s3 sync /home/s3/ $S3_DST --acl public-read
        - echo "***** $GITLAB_USER_NAME pushed $CI_PROJECT_NAME (commit $CI_COMMIT_SHORT_SHA) to $S3_DST$CI_PROJECT_NAME.zip *****"
